spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/second_subject
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: cloud1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: "com.okestro"
  configuration:
    map-underscore-to-camel-case: true
