spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/second_subject
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/second_subject
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 1234
    password: 1111

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: "com.okestro"
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    header:
      Referrer-Policy: strict-origin-when-cross-origin

